esphome:
  name: liquorcabinet
  platform: ESP32
  board: esp32dev
  build_path: ./build

# Enable logging
logger:
  baud_rate: 0    # don't log to the UART we're using for mp3

#  Go look in these files for this stuff.
<<: !include ../core.yaml   # This includes stuff that is common to all my esphome, wifi, OTA, web server.
<<: !include scripts.yaml   
<<: !include sensors.yaml
<<: !include api.yaml
<<: !include mp3.yaml
<<: !include lights.yaml